---
title: "Assignment 4"
author: "Kristin Gill and Sydney Rilum"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(purrr)
library(ggpubr)
```

```{r}
source(here("R", "exponential_growth.R"))

r <- seq(from=0.1, to=1, by=0.1)

t <- seq(from=1, to=30, by=1)

population_data <- data.frame(matrix(ncol= length(r), nrow=length(t)))

rownames(population_data) <- t

colnames(population_data) <- r

initial_population <- 100

for(i in 1:length(t)) {
  for(j in 1:length(r)) {
    population_data[i,j] = exponential_growth(init_pop= initial_population, r = r[j], t=t[i])
  }
}

population_data <- population_data %>% 
  mutate(time = rownames(population_data)) %>% 
  pivot_longer(!time, names_to="r", values_to= "population_size") %>% 
  #filter(r == "0.1") %>% 
  mutate(time = as.numeric(time))

ggplot(data = population_data, aes(x = time,
                                   y = population_size)) +
  facet_wrap(~r, scales = "free") +
  geom_col()+
  theme_minimal() +
  labs(x = "Time (Days)", y = "Population Size")
```

